pre3/AppPre3/urls.py
from django.urls import path
from AppPre3.views import *
from django.contrib.auth.views import LogoutView

urlpatterns=[
    path("", inicio, name="Inicio"),

    #path para login logout editar y registro
    path("login/", inicio_sesion, name="Login"),
    path("register/", registro, name="Registro"),
    path("logout/", LogoutView.as_view(template_name="AppPre3/logout.html"), name="Logout"),
    path("editar/", Editar_Usuario, name="Editar User"),
    path("avatar/", add_avatar, name="Add Avatar"),
    path ("about/",about ,name="About"),

    # path 3era preentrega
    path("compra/", Compra, name="Compra"),
    path("venta/", Venta, name="Venta"),
    path("formulario_User/", form_User, name="Formulario Usuario"),
    path("formulario_Venta/", form_Venta, name="Formulario Venta"),
    path("formulario_Compra/", form_Compra, name="Formulario Compra"),
    path("busque_Compra/", busquedaCompra, name="Busqueda Compra"),
    path("resul_Compra/", resultadoCompra, name="Resultado Compra"),
    path("busque_Venta/", busquedaVenta, name="Busqueda Venta"),
    path("resul_Venta/", resultadoVenta, name="Resultado Venta"),
    
    
    #CRUDs usuario 3era preentrega
    path("leerUsuarios/", leer_usuarios, name="Leer Usuarios"),
    path("eliminarUsuarios/<user_name>/", eliminar_usuario, name="Eliminar Usuario"),
    path("editarUsuarios/<user_name>/", Editar_Usuario, name="Editar Usuario"),


    #CRUDs de ventas

    path("venta/list",ListaVenta.as_view(),name="Leer Venta"),
    path("venta/<int:pk>",DetalleVenta.as_view(),name="Detalle Venta"),
    path("venta/crear/",CrearVenta.as_view(),name="Crear Venta"),
    path("venta/editar/<int:pk>",ActualizarVenta.as_view(),name="Editar Venta"),
    path("venta/borrar/<int:pk>",BorrarVenta.as_view(),name="Borrar Venta"),
]

pre3/pre3/urls.py
from django.contrib import admin
from django.urls import path, include
from AppPre3.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ("AppPre3/", include("AppPre3.urls"))
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pre3/AppPre3/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class usuario(models.Model):

    def __str__(self):
        return f"Nombre: {self.nombre} ---- DNI: {self.DNI} ---- email: {self.email} ---- pais: {self.pais}"

    nombre=models.CharField(max_length=30)
    DNI=models.IntegerField()
    email=models.EmailField()
    pais=models.CharField(max_length=15)

class venta(models.Model):
    nombreVenta=models.CharField(max_length=30)
    fechaVenta=models.DateField()
    montoVenta=models.IntegerField()

class compra(models.Model):
    nombreCompra=models.CharField(max_length=30)
    fechaCompra=models.DateField()
    montoCompra=models.IntegerField()


class Avatar(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="avatares", null=True, blank=True)

pre3/AppPre3/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from AppPre3.models import Avatar


class usuario_Formu(forms.Form):
    nombre_usuario=forms.CharField()
    DNI_usuario=forms.IntegerField()
    email_usuario=forms.EmailField()
    pais_usuario=forms.CharField()

class venta_Formu(forms.Form):
    nombre_Venta=forms.CharField()
    fecha_Venta=forms.DateField()
    monto_Venta=forms.IntegerField()

class compra_Formu(forms.Form):
    nombre_Compra=forms.CharField()
    fecha_Compra=forms.DateField()
    monto_Compra=forms.IntegerField()


class RegistroUsuario(UserCreationForm):
    email=forms.EmailField()
    password1=forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2=forms.CharField(label="Repetir Contraseña", widget=forms.PasswordInput)

    class Meta:
        model= User
        fields= ["username", "email", "first_name", "last_name", "password1", "password2"]



class editarUser(UserCreationForm):
    email=forms.EmailField()
    password1=forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2=forms.CharField(label="Repetir Contraseña", widget=forms.PasswordInput)

    class Meta:
        model= User
        fields= ["email", "first_name", "last_name", "password1", "password2"]


class AvatarFormu(forms.ModelForm):
    class Meta:
        model= Avatar
        fields=["imagen"]

pre3/AppPre3/views.py
from django.shortcuts import render
from django.http import HttpResponse
from AppPre3.models import *
from AppPre3.forms import *
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.


def inicio_sesion(request):
    if request.method=="POST":
        form=AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user=form.cleaned_data.get("username")
            contra=form.cleaned_data.get("password")
            log=authenticate(username=user,password=contra)
            if log:
                login(request,log)
                return render(request, "AppPre3/inicio.html", {"mensaje":f"Bienvenido {log}"})
        else:
            return render(request, "AppPre3/inicio.html", {"mensaje":"Datos Incorrectos"})
    else:
        form=AuthenticationForm()
    return render(request, "AppPre3/login.html", {"formulario":form})



def registro(request):
    if request.method=="POST":
        form=RegistroUsuario(request.POST)
        if form.is_valid():
            username=form.cleaned_data["username"]
            form.save()
            return render(request, "AppPre3/registrohecho.html", {"mensaje":"Usuario Creado"})
    else:
        form=RegistroUsuario()
    return render(request, "AppPre3/registro.html", {"formulario":form})


@login_required
def Editar_Usuario(request):
    user=request.user
    if request.method=="POST":
        form=editarUser(request.POST)
        if form.is_valid():
            info=form.cleaned_data
            user.email=info["email"]
            user.set_password=(info["password1"])
            user.first_name=info["first_name"]
            user.last_name=info["last_name"]
            user.save()
            return render(request, "AppPre3/inicio.html")
    else:
        form=editarUser(initial={"email":user.email,"first_name":user.first_name,"last_name":user.last_name,})
    
    return render(request, "AppPre3/EditarPerfil.html", {"formulario":form, "usuario":user})

@login_required
def add_avatar(request):
    if request.method=="POST":
        form=AvatarFormu(request.POST, request.FILES)
        if form.is_valid():
            usuarioActual= User.objects.get(username=request.user)
            avatar=Avatar(user=usuarioActual, imagen=form.cleaned_data["imagen"])
            avatar.save()
            return render(request, "AppPre3/inicio.html")
    else:
        form=AvatarFormu()

    return render(request, "AppPre3/addAvatar.html", {"formulario":form})
        



def inicio(request):
    return render(request,"AppPre3/inicio.html")
def about(request):
    return render(request,"AppPre3/about.html")
@login_required
def Usuario(request):
    return render(request,"AppPre3/usuario.html")
@login_required
def Venta(request):
    return render(request,"AppPre3/venta.html")
@login_required
def Compra(request):
    return render(request,"AppPre3/compra.html")   


#FORMULARIOS


def form_User(request):
    if request.method=="POST":
        formularioUser=usuario_Formu(request.POST)
        if formularioUser.is_valid():
            infou=formularioUser.cleaned_data
            user=usuario(nombre=infou['nombre_usuario'],DNI=infou['DNI_usuario'],email=infou['email_usuario'],pais=infou['pais_usuario'])
            user.save()
            return render(request, "AppPre3/inicio.html")
    else:
        formularioUser=usuario_Formu()
    return render(request, "AppPre3/formu_User.html", {"formUser":formularioUser})

@login_required
def form_Venta(request):
    if request.method=="POST":
        formularioVenta=venta_Formu(request.POST)
        if formularioVenta.is_valid():
            info=formularioVenta.cleaned_data
            sell=venta(nombreVenta=info["nombre_Venta"], fechaVenta=info["fecha_Venta"], montoVenta=info["monto_Venta"])
            sell.save()
            return render(request, "AppPre3/inicio.html")
    else:
        formularioVenta=venta_Formu()
    return render(request, "AppPre3/formu_Venta.html", {"formVenta":formularioVenta})    

@login_required
def form_Compra(request):
    if request.method=="POST":
        formularioCompra=compra_Formu(request.POST)
        if formularioCompra.is_valid():
            info=formularioCompra.cleaned_data
            buy=compra(nombreCompra=info["nombre_Compra"], fechaCompra=info["fecha_Compra"], montoCompra=info["monto_Compra"])
            buy.save()
            return render(request, "AppPre3/inicio.html")
    else:
        formularioCompra=compra_Formu()
    return render(request, "AppPre3/formu_Compra.html", {"formCompra":formularioCompra})



    #BUSQUEDA
@login_required
def busquedaCompra(request):
    return render(request, "AppPre3/busq_Compra.html")

@login_required
def busquedaVenta(request):
    return render(request, "AppPre3/busq_Venta.html")   

@login_required
def resultadoCompra(request):
    if request.GET["compra"]:
        busqueda=request.GET["compra"]
        resul=compra.objects.filter(nombreCompra__icontains=busqueda)
        return render(request, "AppPre3/resul_Compra.html", {"resultado":resul,"objeto":busqueda})
    else:
        respuesta="No enviaste datos"
    return render(request, "AppPre3/resul_Compra.html", {"mensaje":respuesta})

@login_required
def resultadoVenta(request):
    if request.GET["venta"]:
        busqueda=request.GET["venta"]
        resul=venta.objects.filter(nombreVenta__icontains=busqueda)
        return render(request, "AppPre3/resul_Venta.html", {"resultado":resul,"objeto":busqueda})
    else:
        respuesta="No enviaste datos"
    return HttpResponse(respuesta)



    #CRUD USUARIO 3era preentrega

@login_required
def leer_usuarios(request):
    user=usuario.objects.all()
    return render(request, "AppPre3/leer_usuarios.html", {"datos":user})

@login_required
def eliminar_usuario(request, user_name):
    user=usuario.objects.get(nombre=user_name)
    user.delete()
    usuarios=usuario.objects.all()
    return render(request, "AppPre3/leer_usuarios.html",{"datos":usuarios})

@login_required
def editar_usuario(request, user_name):
    user=usuario.objects.get(nombre=user_name)
    if request.method=="POST":
        formularioUser=usuario_Formu(request.POST)
        if formularioUser.is_valid():
            infou=formularioUser.cleaned_data
            user.nombre=infou["nombre_usuario"]
            user.DNI=infou["DNI_usuario"]
            user.email=infou["email_usuario"]
            user.pais=infou["pais_usuario"]
            user.save()
            return render(request, "AppPre3/inicio.html")
    else:
        formularioUser=usuario_Formu(initial={"nombre_usuario":user.nombre, "DNI_usuario":user.DNI, "email_usuario":user.email, "pais_usuario":user.pais})
    return render(request, "AppPre3/editar_usuario.html", {"formUser":formularioUser, "nombre_usuario":user_name})



class ListaVenta(LoginRequiredMixin, ListView):
    model= venta

class DetalleVenta(LoginRequiredMixin, DetailView):
    model=venta

class CrearVenta(LoginRequiredMixin, CreateView):
    model=venta
    success_url="/AppPre3/venta/list"
    fields=["nombreVenta","fechaVenta","montoVenta"]

class ActualizarVenta(LoginRequiredMixin, UpdateView):
    model=venta
    success_url="/AppPre3/venta/list"
    fields=["nombreVenta","fechaVenta","montoVenta"]


class BorrarVenta(LoginRequiredMixin, DeleteView):
    model=venta
    success_url="/AppPre3/venta/list"
    

pre3/AppPre3/templates/AppPre3/EditarPerfil.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

Edita los datos de usuario

{% endblock %}

{% block texto %}

<form action="" method="POST" class="text-white mt-0"> {% csrf_token %}

    {{formulario.as_p}}
    
    <button type="submit"class="btn btn-primary btn-xl">Editar</button>
    
    </form>

{% endblock %}

{% block botones %}

<h2 class="text-white mt-0">Formularios y busqueda</h2>
<hr class="divider divider-light" />
<a class="btn btn-light btn-xl" href="{% url 'Venta' %}">Ventas</a>
<a class="btn btn-light btn-xl" href="{% url 'Compra' %}">Compras</a>

{% endblock %}

pre3/AppPre3/templates/AppPre3/about.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

Hola mi nombre es Alejandro Serrano

{% endblock %}

{% block texto1 %}

Soy de Venezuela-Estado Táchira, tengo 30 años, graduado en Ingeniería Industrial.
Me gusta el rock, los video juegos y pasar tiempo de calidad con mi familia y mis mascotas. Tengo un emprendimiento y actualmente me ha llamado la atención todo lo que circunda a la programación, por lo tanto, estoy estudiando ingeniería informática y trato de alimentar mas mi conociemiento realizando cursos de diferentes lenguajes de programación.
Me caracterizo por ser responsable, abierto a nuevos conocimientos, me apasionan todas las ramas de la ciencia y quisiera llevar mi carrera hacia el análisis de datos y la inteligencia artificial aplicada a la astrología.
Valoro mucho la amistad, el compromiso y la responsabilidad en general. <br>
El proyecto final se creo con la idea de llevar un control en el registro de compra y ventas de mi emprendimiento.


{% endblock %}

pre3/AppPre3/templates/AppPre3/busq_Compra.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

BUSQUEDA DE COMPRA

{% endblock %}


{% block texto %}
Porfavor indica que compra deseaas buscar 
    <form action="/AppPre3/resul_Compra/" method="GET">

        <input type="text" name="compra" id="compra">
        <input type="submit" value="Buscar" class="btn btn-primary btn-xl">

    </form>
    {% endblock %}

    {% block botones %}
    
    <h2 class="text-white mt-0">Formularios y busqueda</h2>
    <hr class="divider divider-light" />
    <a class="btn btn-light btn-xl" href="{% url 'Venta' %}">Ventas</a>
    <a class="btn btn-light btn-xl" href="{% url 'Formulario Compra' %}">Formulario</a>
    
    {% endblock %}

pre3/AppPre3/templates/AppPre3/busq_Venta.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

BUSQUEDA DE COMPRA

{% endblock %}


{% block texto %}
Porfavor indica que venta deseaas buscar 
    <form action="/AppPre3/resul_Venta/" method="GET">

        <input type="text" name="venta" id="venta">
        <input type="submit" value="Buscar">


    </form>
    {% endblock %}

    {% block botones %}
    
    <h2 class="text-white mt-0">Formularios y CRUD</h2>
    <hr class="divider divider-light" />
    <p class="text-white-75 mb-4"></p>
    <a class="btn btn-light btn-xl" href="{% url 'Compra' %}">Compra</a>
    <a class="btn btn-light btn-xl" href="{% url 'Crear Venta' %}">Agregar</a>
    <a class="btn btn-light btn-xl" href="{% url 'Leer Venta' %}">Ver lista</a>

    
    {% endblock %}

pre3/AppPre3/templates/AppPre3/formu_Compra.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

FORMULARIO DE COMPRA

{% endblock %}


{% block texto %}

Porfavor completa los campos con los datos de tu compra
    <form action="" method="POST" style="margin-left: 25%; color: white;"> {% csrf_token %}
        <table>
            {{formCompra.as_table}}
        </table>

        <input type="submit" value="Confirmar" class="btn btn-primary btn-xl" style="margin-left: -25%;margin-top: 1%;">

    </form>
    {% endblock %}

    {% block botones %}
    
    <h2 class="text-white mt-0">Formularios y busqueda</h2>
    <hr class="divider divider-light" />
    <a class="btn btn-light btn-xl" href="{% url 'Venta' %}">Ventas</a>
    <a class="btn btn-light btn-xl" href="{% url 'Busqueda Compra' %}">Busqueda</a>
    
    {% endblock %}

pre3/AppPre3/templates/AppPre3/formu_Venta.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

FORMULARIO DE VENTA

{% endblock %}


{% block texto %}
Porfavor completa los campos con lo datos de tu venta
    <form action="" method="POST" style="margin-left: 25%; color: white;"> {% csrf_token %}
        <table>
            {{formVenta.as_table}}
        </table>

        <input type="submit" value="Confirmar" class="btn btn-primary btn-xl" style="margin-left: -25%;margin-top: 1%;">

    </form>
    {% endblock %}

    {% block botones %}
    
    <h2 class="text-white mt-0">CRUD y busqueda</h2>
    <hr class="divider divider-light" />
    <a class="btn btn-light btn-xl" href="{% url 'Compra' %}">Compras</a>
    <a class="btn btn-light btn-xl" href="{% url 'Busqueda Venta' %}">Busqueda</a>
<a class="btn btn-light btn-xl" href="{% url 'Leer Venta' %}">Ver lista</a>
    
    {% endblock %}

pre3/AppPre3/templates/AppPre3/login.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

Ingresa tu usuario y contraseña para iniciar sesión, si no los tienes crealos aqui:
<a class="btn btn-primary btn-xl" href="{% url 'Registro' %}">Registrate</a>

{% endblock %}

{% block texto1 %}

<form action="" method="POST" class="text-white font-weight-bold"> {% csrf_token %}

{{formulario.as_p}}

<button type="submit" class="btn btn-primary btn-xl">Iniciar sesion</button>

</form>

{% endblock %}

pre3/AppPre3/templates/AppPre3/logout.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

Sesión finalizada

{% endblock %}

pre3/AppPre3/templates/AppPre3/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Proyecto final</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'AppPre3/assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppPre3/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'Inicio' %}">Proyecto final Serrano</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">


                        {% if request.user.is_authenticated %}

                       
                        <li class="nav-item"><a class="nav-link" href="{% url 'Venta' %}">Venta</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Compra' %}">Compra</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Editar User' %}">Editar usuario</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Logout' %}">Cerrar sesión</a></li>
                        <li class="nav-item"><p class="nav-link">Hola {{user.first_name}}</p></li>
                        {% with user.avatar_set.first as img %}
                            {% if img %} 
                            <img src="{{img.imagen.url}}" alt="No se encuentra" style="max-width: 5%;">
                            {% endif %} 
                            {% endwith %}
                        </li>
                        
                        {% else %}

                        <li class="nav-item"><a class="nav-link" href="{% url 'Registro' %}">Registrarse</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Login' %}">Iniciar sesión</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'About' %}">About</a></li>

                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">
                            
                            {% block titulo1 %}


                            {% endblock %}
                            
                        </h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">
                            {% if request.user.is_authenticated %}

                            {% block texto %}


                            {% endblock %}


                            {% else %}
                            
                            {% block texto1 %}


                            {% endblock %}
                            {% endif %}


                        </p>
                        
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        {% if request.user.is_authenticated %}
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">

                        

                        {% block botones %}

                        {% endblock %}

                        
                    </div>
                </div>
            </div>
        </section>
                    {% else %}
                    {% endif %}
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2023 - Alejandro Serrano</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'AppPre3/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

pre3/AppPre3/templates/AppPre3/registrohecho.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}


{{mensaje}}

{% endblock %}

{% block texto1 %}

<a class="btn btn-primary btn-xl" href="{% url 'Login' %}">Inicia Sesión</a>


{% endblock %}

pre3/AppPre3/templates/AppPre3/resul_Compra.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

BUSQUEDA DE COMPRA

{% endblock %}


{% block texto %}


    <p class="text-white font-weight-bold">Estas buscando: {{objeto}}</p>

    {% for x in resultado %}

        <p class="text-white font-weight-bold">Nombre: {{x.nombreCompra}} ---- Comprado en: {{x.fechaCompra}} ---- Monto: {{x.montoCompra}}</p>

    {% endfor %}
{% endblock %}

{% block botones %}
    
    <h2 class="text-white mt-0">Formularios y busqueda</h2>
    <hr class="divider divider-light" />
    <p class="text-white-75 mb-4">Recomendacion: Escoge cualquier formulario, despues podras escoger busqueda</p>
    <a class="btn btn-light btn-xl" href="{% url 'Venta' %}">Ventas</a>
    
    {% endblock %}

pre3/AppPre3/templates/AppPre3/venta.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

ESPACIO DE VENTAS

{% endblock %}

{% block texto %}
Podras seleccionar: <br>
Agregar: para registrar una ventas <br>
Busqueda: para encontrar las ventas <br>
Ver listas: para ver todas las ventas registradas <br>

{% endblock %}

{% block botones %}
<h2 class="text-white mt-0">Formularios, busqueda y CRUD</h2>
<hr class="divider divider-light" />
<p class="text-white-75 mb-4">Escoge una opción</p>
<a class="btn btn-light btn-xl" href="{% url 'Formulario Venta' %}">Agregar</a>
<a class="btn btn-light btn-xl" href="{% url 'Busqueda Venta' %}">Busqueda</a>
<a class="btn btn-light btn-xl" href="{% url 'Leer Venta' %}">Ver lista</a>


{% endblock %}

pre3/AppPre3/templates/AppPre3/venta_detail.html
{% extends "AppPre3/padre.html" %}

{% load static %} 


{% block titulo1 %}

Estos son los detalles de la venta

{% endblock %}

{% block texto %}
    
    <p class="text-white font-weight-bold">Nombre: {{venta.nombreVenta}}</p>
    <p class="text-white font-weight-bold">Nombre: {{venta.fechaVenta}}</p>
    <p class="text-white font-weight-bold">Nombre: {{venta.montoVenta}}</p>


        <a class="btn btn-primary btn-xl" href="{% url 'Leer Venta' %}">Regresar</a>
    
    
    {% endblock %}
    {% block botones %}
    
    <h2 class="text-white mt-0">Formularios y busqueda</h2>
    <hr class="divider divider-light" />
    <a class="btn btn-light btn-xl" href="{% url 'Crear Venta' %}">Agregar</a>
    <a class="btn btn-light btn-xl" href="{% url 'Leer Venta' %}">Ver lista</a>
    <a class="btn btn-light btn-xl" href="{% url 'Compra' %}">Compras</a>
    
    {% endblock %}